# Generated by Django 3.2.7 on 2026-01-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shabarimala', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
