# Generated by Django 3.2.7 on 2026-01-06 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shabarimala', '0003_emergency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_reports', to='shabarimala.police'),
        ),
    ]
