# Generated by Django 3.2.7 on 2026-01-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shabarimala', '0004_alter_emergency_reporter'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('phone', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('specialization', models.CharField(max_length=100)),
                ('hospital', models.CharField(max_length=200)),
                ('experience_years', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
