# Generated by Django 3.2.7 on 2026-01-06 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shabarimala', '0005_medicalstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='medical_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergency',
            name='medical_response_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergency',
            name='medical_staff_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_emergencies', to='shabarimala.medicalstaff'),
        ),
    ]
